### ISSUE TITLE
[Epic] Add test harnesses and tests

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-agent#13]
- [ ] Add unit tests with JUnit, Mockito
- [ ] Add functional tests with [MockServer](https://www.mock-server.com/)
- [ ] Add integration tests with podman, a sample application with the agent attached, and a real Cryostat instance
