### ISSUE TITLE
[Epic] Kubernetes/OpenShift awareness

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-agent#381]
There are various things we can try to do to improve the Agent's ergonomics when it detects it is running in Kubernetes/OpenShift.

- [x] #382
- [ ] watch mode as specified in https://github.com/cryostatio/cryostat-agent/pull/234#issue-1946139083
- [x] ability to mount Agent JAR as a volume into workload Pod, or copy in (a la `oc cp` or `oc rsync`), then do the equivalent to `oc exec` to launch the Agent JAR
- [x] can the Agent inspect itself/its Pod to look for annotations? These could also be used to set configuration property values, ex. the Cryostat server URI, so that the configuration can be done by annotation rather than environment variable
- [ ] [ability to detach and stop the Agent process separately from the workload process. This would facilitate an ability to restart the Agent, which would be useful when combined with loading configuration properties from annotations or other sources that do not force the Pod to rolling restart](https://github.com/cryostatio/cryostat-agent/issues/404)
- [ ] #477

**Comment by andrewazores** [comment]
Another idea would be for the Agent to determine its own Pod, Deployment, and Namespace information to create environment nodes and wrap those around the target node that it publishes to represent itself. This way Agent would appear in Cryostat with more information about the context of the particular instance.

We might also consider some option on the Cryostat side, or within the cryostat-web Topology view, to allow merging these. All of the Agents will appear as their own independent Realms, but there can be duplication across Namespaces or Deployments, so it would be nice to be able to represent that more cleanly.
